export const HOURS_PER_DAY = 24;

export const SECONDS_PER_MINUTE = 60;
export const SECONDS_PER_HOUR = 60 * SECONDS_PER_MINUTE;
export const SECONDS_PER_DAY = HOURS_PER_DAY * SECONDS_PER_HOUR;

export const MS_PER_SECOND = 1_000;
export const MS_PER_DAY = SECONDS_PER_DAY * MS_PER_SECOND;
